controllers:
    resource: ../src/Controller/
    type: attribute
    prefix: /api

kernel:
    resource: ../src/Kernel.php
    type: annotation

api_login_check:
    path: /api/login_check
    methods: POST

update_customer:
    path: /api/users/{id}
    controller: App\Controller\CustomerController::updateCustomer
    methods: [PUT]
